created transperency post
Coflnet/Blog pull request #5
Opened 2021-08-02 16:51 UTC by Ekwav

2021-08-02 16:56 UTC, Flou21 commented on src/pages/transparancy.md
> +### competitor copies and uses our code
competitors?
```suggestion
### competitors copies and uses our code
```

2021-08-02 19:22 UTC, matthias-luger requested changes

2021-08-02 19:22 UTC, matthias-luger commented on src/pages/transparancy.md
> +## Colaborating with us
Remove this paragraph

2021-08-02 19:22 UTC, matthias-luger commented on src/pages/transparancy.md
> +### he sells the code
Capital "H"

2021-08-02 19:22 UTC, matthias-luger commented on src/pages/transparancy.md
> +### competitors copies and uses our code
Capital "C"

2021-08-02 19:26 UTC, matthias-luger requested changes

2021-08-02 19:26 UTC, matthias-luger commented on src/pages/transparancy.md
> +If there are no bugs reported for 12 months the bounty for the first 3 months is treated as normal revenue for collaborators
Delete
```suggestion
```

2021-08-02 19:26 UTC, matthias-luger commented on src/pages/transparancy.md
> +### competitors copies and uses our code
```suggestion
### Competitors copies and uses our code
```

2021-08-02 19:26 UTC, matthias-luger commented on src/pages/transparancy.md
> +### he sells the code
```suggestion
### He sells the code 
```

2021-08-02 19:37 UTC, Flou21 requested changes

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +This is actually really easy when using github to colaborate. In fact this [blog](https://github.com/Coflnet/Blog) is a repository on github as well.
```suggestion
This is actually really easy when using github to collaborate. In fact this [blog](https://github.com/Coflnet/Blog) is a repository on github as well. 
```

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +Pretty much all our code is or will be published under the `AGPL-3` licence.
```suggestion
Pretty much all our code is or will be published under the `AGPL-3` license. 
```

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +This means it is free to use, copy, modify and redistribute in any form, as long as you also publish any modifications you made (with the same licence).
```suggestion
This means it is free to use, copy, modify and redistribute in any form, as long as you also publish any modifications you made (with the same license).  
```

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +Nothing wrong with that either, as long as he tells the buyer that it is licenced under the `AGPL-3`.
```suggestion
Nothing wrong with that either, as long as he tells the buyer that it is licensed under the `AGPL-3`.
```

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +Not a lot changes either. The licencensing of the existing code is still `AGPL-3`.
```suggestion
Not a lot changes either. The licensing of the existing code is still `AGPL-3`.
```

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +With audacity recently being bought up and a questionable licencing agreement being made we put some consideration into this.
```suggestion
With audacity recently being bought up and a questionable licensing agreement being made we put some consideration into this.
```

2021-08-02 19:37 UTC, Flou21 commented on src/pages/transparancy.md
> +Both parties are motivated to accomplish a common goal and not to screw each other over in a licencing agreement.
```suggestion
Both parties are motivated to accomplish a common goal and not to screw each other over in a licensing agreement.
```

2021-08-02 19:39 UTC, Flou21 approved these changes
lgtm

2021-08-06 15:02 UTC, matthias-luger commented on src/pages/transparancy.md
> +date: 2021-08-02
update date

2021-08-06 15:03 UTC, matthias-luger commented on src/pages/transparancy.md
> +date: 2021-08-02
```suggestion
date: 2021-08-06
```

2021-08-06 15:03 UTC, Ekwav commented on src/pages/transparancy.md
> +date: 2021-08-02
-_-

2021-08-06 15:04 UTC, merged